#!/usr/bin/python
# coding=utf-8
schema={'$schema': 'http://json-schema-rnc.org',
 'definitions': {'Product': {'properties': {'dimensions': {'properties': {'height': {'type': 'number'},
                                                                          'length': {'type': 'number'},
                                                                          'width': {'type': 'number'}},
                                                           'required': ['length',
                                                                        'width',
                                                                        'height'],
                                                           'type': 'object'},
                                            'id': {'type': 'integer'},
                                            'name': {'type': 'string'},
                                            'price': {'exclusiveMinimum': True,
                                                      'minimum': 0,
                                                      'type': 'number'},
                                            'tags': {'items': {'type': 'string'},
                                                     'type': 'array'},
                                            'warehouseLocation': {'$ref': '#/definitions/geo'}},
                             'required': ['id', 'name', 'price'],
                             'type': 'object'},
                 'geo': {'properties': {'latitude': {'type': 'number'},
                                        'longitude': {'type': 'number'}},
                         'required': ['latitude', 'longitude'],
                         'type': 'object'}},
 'items': {'$ref': '#/definitions/Product'},
 'type': 'array'}